### ISSUE TITLE
On adding a new dat, getting a hyperdrive error

### ISSUE THREAD

**Issue by ryanramage** [karissa/dat-server#8]
```
> dat-server@1.0.1 start /Volumes/untitled/github/forks/dat-server
> npm run watch & node cli.js


> dat-server@1.0.1 watch /Volumes/untitled/github/forks/dat-server
> watchify -t [ babelify --presets [ react ] ] frontend.js -o static/bundle.js

http://localhost:8080
listening
/Volumes/untitled/github/forks/dat-server/node_modules/hyperdrive-archiver/node_modules/hyperdrive/index.js:878
      return storage(path.join(folder, 'content', name))
             ^

TypeError: storage is not a function
    at Storage.content [as create] (/Volumes/untitled/github/forks/dat-server/node_modules/hyperdrive-archiver/node_modules/hyperdrive/index.js:878:14)
    at Storage.openKey (/Volumes/untitled/github/forks/dat-server/node_modules/hyperdrive-archiver/node_modules/hypercore/lib/storage.js:154:34)
    at Storage.openKey (/Volumes/untitled/github/forks/dat-server/node_modules/hyperdrive-archiver/node_modules/hypercore/lib/storage.js:153:47)
    at Feed._open (/Volumes/untitled/github/forks/dat-server/node_modules/hyperdrive-archiver/node_modules/hypercore/index.js:182:17)
    at open (/Volumes/untitled/github/forks/dat-server/node_modules/hyperdrive-archiver/node_modules/hypercore/index.js:97:10)
    at run (/Volumes/untitled/github/forks/dat-server/node_modules/hyperdrive-archiver/node_modules/thunky/index.js:19:5)
    at Feed.thunk [as _ready] (/Volumes/untitled/github/forks/dat-server/node_modules/hyperdrive-archiver/node_modules/thunky/index.js:13:5)
    at new Feed (/Volumes/untitled/github/forks/dat-server/node_modules/hyperdrive-archiver/node_modules/hypercore/index.js:82:8)
    at Feed (/Volumes/untitled/github/forks/dat-server/node_modules/hyperdrive-archiver/node_modules/hypercore/index.js:26:39)
    at done (/Volumes/untitled/github/forks/dat-server/node_modules/hyperdrive-archiver/node_modules/hyperdrive/index.js:789:62)
```

**Comment by ryanramage** [comment]
Sorry have not had time to look closer. WIll have a peek more this weekend.

**Comment by karissa** [comment]
Are you sure you're using the latest versions of all the dependencies? Try `rm -rf node_modules && npm install`

**Comment by ryanramage** [comment]
Yeah I tried and with no luck. Also I tried locking down the versions to the exact ones specified in the package.json, and that did not help either.

**Comment by karissa** [comment]
@ryanramage can you try now? just published a new version of dat-server

**Comment by ryanramage** [comment]
@karissa I updated dat-server, rm -r node_modules, npm i, npm start 

Still same error. This does not happen for you by chance?

My node and npm version
```
®[dat-server]$ node -v
v8.7.0
®[dat-server]$ npm -v
5.4.2
```

**Comment by victorperin** [comment]
Hello guys, I'm getting the same error here too. I could get sometime digging arround it to see whats the problem.
